name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Determine environments
        id: env
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "SUPABASE_PROJECT_ID=${{ secrets.SUPABASE_PROJECT_ID_PROD }}" >> $GITHUB_ENV
          else
            echo "SUPABASE_PROJECT_ID=${{ secrets.SUPABASE_PROJECT_ID_DEV }}" >> $GITHUB_ENV
          fi

      # in case we need any edge functions
      # - name: Deploy Edge Functions
      #   env:
      #     SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      #   run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID